name: Test and Package VS Code Extension

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build (${{ matrix.os }})
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v7

    - name: Setup Node.js
      uses: actions/setup-node@v7
      with:
        node-version: 26
        cache: 'npm'
        cache-dependency-path: |
          package-lock.json
          parser/package-lock.json

    - name: Install Dependencies
      run: npm ci
    - name: Install parser dependencies
      run: npm --prefix parser ci

    - name: Package Extension
      run: npm run package
